import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'
import Header from '../components/Header'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'


export default function Home() {

  const { data: session } = useSession()
  console.log(session);
  if (!session) {
    return <Login />
  }
  return (
    <div>
      <Head>
        <title>Facebook 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='flex'>
        {/*Sidebar  */}
        <Sidebar />
        {/* Feed */}
        <Feed />
      </main>

      {/* Widgets */}
    </div>
  )
}
export async function getServerSideProps(context) {
  // Get the User
  const session = await getSession(context);
  return {
    props: {
      session,
    }
  }

}
